server:
  port: 8080

spring:
  cloud:
    gateway:
jwt:
  secret: mysupersecurejwtsecretkeythatismorethan32byteslong

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: TRACE