spring.application.name=ai-service
server.port=8083

#spring.datasource.url=jdbc:postgresql://lovable-postgres:5432/ai_db
spring.datasource.url=jdbc:postgresql://localhost:5435/ai_db

spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ================= KAFKA =================
#spring.kafka.bootstrap-servers=lovable-kafka:9092
spring.kafka.bootstrap-servers=localhost:9091


spring.kafka.consumer.group-id=ai-service-group-v4
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.lovable.ai_service.dto.AiRequestEvent

spring.kafka.consumer.properties.spring.json.type.mapping=com.lovable.ai_service.dto.AiRequestEvent:com.lovable.ai_service.dto.AiRequestEvent
# Increase time allowed between polls (Default is usually 300000ms, but check your version)
spring.kafka.consumer.properties.max.poll.interval.ms=600000

# Optionally reduce the number of messages processed at once
# so the total batch time stays low
spring.kafka.consumer.max-poll-records=1
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka.clients.consumer=INFO
# Enable idempotent producer (recommended)
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# Kafka Connection
spring.kafka.listener.missing-topics-fatal=false

## ================= SPRING AI =================
#spring.ai.google.ai.api-key=AIzaSyAOg79w96DE7gNcns_z0RT78XLgQ9oGxdw
#spring.ai.google.ai.chat.options.model=gemini-2.5-flash
#spring.ai.openai.api-key=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
#spring.ai.openai.chat.options.model=gpt-4o




# --- LOCAL OLLAMA (For Embeddings) ---
# This is the "primary" URL Spring AI uses for all auto-configured beans
# =========================
# LOCAL OLLAMA (Embeddings)
# =========================
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.embedding.options.model=mxbai-embed-large:latest
#spring.ai.ollama.embedding.options.endpoint=/api/embeddings

# =========================
# CLOUD CHAT
# =========================
# Connection
spring.ai.ollama.base-url=http://localhost:11434

# Chat Configuration (Cloud)
spring.ai.ollama.chat.options.model=qwen3-coder:480b-cloud

# Embedding Configuration (Local)
spring.ai.ollama.embedding.options.model=mxbai-embed-large