server {
    listen 80;
    server_name b08e0f1d-82ab-4e1a-b1fd-b4d16f3bcb1f.localhost;

    location / {
        proxy_pass http://host.docker.internal:30021;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}