server {
    listen 80;
    server_name bae5c2f9-78ae-4d56-9be3-39aa26d3b5cb.localhost;

    location / {
        proxy_pass http://host.docker.internal:30009;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}