events {}

http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    # Include all dynamically generated project configurations
    include /etc/nginx/conf.d/dynamic/*.conf;

    # Default server for unmatched domains
    server {
        listen 80 default_server;
        server_name _;
        return 404;
    }

}